language: node_js
dist: xenial
os: linux
node_js: 14
services: xvfb
cache: npm
before_install:
  - npm config set scripts-prepend-node-path true
install:
  - alias python=python2
  - npm install
script:
  - npm run check
  - npm run build
  - travis_retry npm run test
  - npm run docs:publish
deploy:
  provider: pages
  edge: true
  strategy: git
  cleanup: false
  token: $GH_TOKEN
  local_dir: docs/.vuepress/dist
  keep_history: true
  target_branch: gh-pages
  commit_message: 'Commit sha: %{git_sha}'
  name: 'traviscibot'
  email: 'deploy@travis-ci.org'
  verbose: true
  on:
    branch: master
